# Generated by Django 5.0.8 on 2024-08-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
